### ISSUE TITLE
Use built release for CI tests

### ISSUE THREAD

**Issue by JuroOravec** [EmilStenstrom/django-components#405]
This follows up on @EmilStenstrom's [suggestion of having a CI step to catch errors in releases](https://github.com/EmilStenstrom/django-components/pull/404#issuecomment-2016774398).

The above-referenced error was caused because we currently use the source code for tests. And the published package behaved differently than source code (it missed some files).

After a quick search, I came across the `build` command of `setup.py`. We could use this to build the source code into a distribution, and then use the latter in tests.

1) Build the package:
	```sh
	python setup.py build
	```
	This builds the packages into `./build/lib`:
	
	<img width="282" alt="Screenshot 2024-03-24 at 13 32 16" src="https://github.com/EmilStenstrom/django-components/assets/25986782/a4ecbaf7-7891-4be5-8fda-3a37611ae9c2">

2) Import the built package in tests:

	Instead of `django_components`, we import from `build.lib.django_components`:

	```py
	from build.lib.django_components import autodiscover, component
	...
	```

3) Now, when we run tests, we will use the distro version of the package.

Considerations:
- If we replace all `django_components` imports in tests with `build.lib.django_components`, then we MUST build before can test. This can be annoying for development. So instead, we could use the build conditionally with a feature flag, so we can decide whether to test with source code or distro:

	```yaml
	if IS_CI:  # taken from env vars
		from build.lib.django_components import autodiscover, component
	else:
		from django_components import autodiscover, component
	```

	And then trigger it only in CI like so:
	```yaml
	jobs:
	  build:
	    ...
	    steps:
	      ...
	      - name: Run tests
	         run: IS_CI=true tox
	```

Thoughts?
