### ISSUE TITLE
Release 0.93 did not trigger documentation build

### ISSUE THREAD

**Issue by dalito** [EmilStenstrom/django-components#625]
The docs for the newest release 0.93 were not created. The job was skipped, see https://github.com/EmilStenstrom/django-components/actions/workflows/docs.yml

It could be a missing trigger on new tags. Something like:
```
on:
  push:
    tags:
      - '[0-9].[0-9]+'
    ....
```

I also wonder if mike expects versions with a leading "v", so a tag "v0.93" which is more common for version tags.
